# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a3a51de0778808b0c6bdf4e4ff0b89d6"
name = "instamart-aichatbot"
handle = "instamart-aichatbot"
application_url = "https://idaho-volt-speak-wells.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "instmart-ai-chatbot.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://idaho-volt-speak-wells.trycloudflare.com/auth/callback",
  "https://idaho-volt-speak-wells.trycloudflare.com/auth/shopify/callback",
  "https://idaho-volt-speak-wells.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
